spring:
#  # Redundant but explicit activation of the 'dev' profile
#  # Will automatically apply when correct naming convention is used
#  config:
#    activate:
#      on-profile: dev
  app:
    client-url: https://www.memoize.in
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
logging:
  level:
    root: INFO
    com.zaxxer.hikari: WARN
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO